language: clojure
lein: 2.9.1
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
script: lein with-profile +dev:+1.8:+1.9 test
jobs:
  include:
    - stage: cljs-test
      jdk: openjdk11
      script: lein doo node test once
