language: clojure
lein: 2.8.1
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  - openjdk8
script: lein with-profile dev:1.9:1.10 test
jobs:
  include:
    - stage: cljs-test
      jdk: oraclejdk8
      script: lein doo node test once
